Test mock: Install /usr/sbin/useradd
Otherwise mock errors with:

    ERROR: Could not find useradd in chroot, maybe the install failed?

On Fedora Rawhide (32 at this moment).

Since we have custom mock config, we don't get all the package mock
thinks are there by default.

See also https://github.com/rpm-software-management/mock/issues/382